lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/var/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/var/jwt/public.pem'  # required for token verification
    pass_phrase:      'klasor' # required for token creation, usage of an environment variable is recommended
    token_ttl:        360000 #100 hour
